### ISSUE TITLE
Add some kind of Server list

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite.github.io#100]
So I just openend the Server-List thread on the forum
https://forum.cuberite.org/thread-1435.html

And this seems kind of noisy. I would suggest something like the news page(s) where you could add your server as a PR. This gives us the option to moderate posted servers and maybe implement some checks if the servers are actually still responding and remove the after a certain time of absence.

Or maybe have an actual server list on the webpage where we moderate onsite but I don't think this is worth it implementing the whole thing.

I'd like to do this but I only can write 90s plain HTML web pages and can't fully grasp how the website actually works.

**Comment by bearbin** [comment]
I'd say this is not worth it - there are existing discovery mechanisms for Minecraft servers, and I don't want to get into moderation, that's a whole heap of issues. Have the demo server up but I think other than that users can find their own servers.

**Comment by tigerw** [comment]
> 90s plain HTML web pages

the best kind!

A dedicated list of Cuberite servers could be useful in showing off readiness for real world use. But I suspect that number is (alas) small enough that the current forum post will suffice. I can't edit the post to add the demo server though.

**Comment by mathiascode** [comment]
@12xx12 @tigerw You should now have permissions to edit the post. I used to update the list irregularly, but haven't had time nor interest in a while.

**Comment by mathiascode** [comment]
Closing, as there doesn't seem to be much interest and this repository probably isn't the right location for something like this. The forum thread is up for grabs if someone has time to maintain a server list.
