### ISSUE TITLE
Windows Artifact not found or access denied.

### ISSUE THREAD

**Issue by gabrielfeket** [cuberite/cuberite.github.io#107]
When click to download for Windows platform (any architecture) receive an error: {"message":"Artifact not found or access denied."}
from: https://ci.appveyor.com/api/projects/cuberite/cuberite/artifacts/Cuberite.zip?job=Windows-x86&pr=false&branch=master

**Comment by bearbin** [comment]
I suspect this is because there hasn't been a new build for a while, so the old builds got deleted. I've run another build, can you try downloading in 1/2 an hour and see if it's fixed.

**Comment by bearbin** [comment]
Closing, the above was correct. You can now download using the published links.
