### ISSUE TITLE
Update Favicon

### ISSUE THREAD

**Issue by navopw** [cuberite/cuberite.github.io#11]
The favicon is the old MCServer icon -> http://cuberite.org/assets/icon_256.png

~Navo

**Comment by NiLSPACE** [comment]
Well, we don't even have a new logo yet ;) We're still discussing that [here](http://forum.mc-server.org/showthread.php?tid=2000).

**Comment by navopw** [comment]
Ah ok, i thought this is the new logo -> http://cuberite.org/assets/cuberite2-6.png

**Comment by bearbin** [comment]
Nope, @SphinxC0re changed it without telling anybody :p 

If you have any thoughts on a logo, please do say in the forum thread.

**Comment by navopw** [comment]
Alright :) Actually i like the logo from @SphinxC0re ^~^
Better than the old MCServer logo :+1:

**Comment by sphinxc0re** [comment]
Thank you very much, but I have to say that it was not intended by me to set the new logo as a standard all by myself. It is just a test and I wanted to change the Logo every week or so to see which one is the best
