### ISSUE TITLE
There should be a mention of the cuberite email

### ISSUE THREAD

**Issue by NiLSPACE** [cuberite/cuberite.github.io#18]
We currently have an email, but it isn't mentioned anywhere except the issue it was created in (cuberite/cuberite#2475).

I think in the support tab there should be a mention of `support@cuberite.org`

**Comment by mathiascode** [comment]
If someone replies to emails sent to the email address, I can add this.

**Comment by mathiascode** [comment]
How does this look? http://final.cuberite.ga/support/

**Comment by sphinxc0re** [comment]
nice

**Comment by madmaxoft** [comment]
I think the email is more for the cases when something withour infrastructure goes wrong - the forum misbehaves or the domain gets misconfigured. We don't want regular issues on that email. Or do we?

**Comment by sphinxc0re** [comment]
No, not really. If someones business is on fire, we should be available :smile:

**Comment by mathiascode** [comment]
Fixed in this PR, which is now merged: https://github.com/cuberite/cuberite.github.io/pull/23
