### ISSUE TITLE
Brighter color scheme

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#19]
<del>The site looks way too dark after I corrected the contrast of my screen (you can't even see the hover effect on buttons well), and others have requested a change as well.</del>

<del>I suggested a green color scheme in this thread (because green is fresh, other server projects don't use the color, and Cuberite's colored icon contains green :P): http://forum.mc-server.org/showthread.php?tid=2049&pid=23155</del>

We'll keep the dark color scheme.

**Comment by mathias-github** [comment]
Any thoughts about this?

**Comment by madmaxoft** [comment]
A bit too green for my taste, but I'm no designer.

**Comment by mathiascode** [comment]
Actually, let's keep the dark color scheme. The background discussion has been going on for too long. 

I created a new pull request where I used a slightly ligher gray color for the background, since the old  looked pitch black on some screens.

This issue can be closed.
