### ISSUE TITLE
The website should mention the IRC channel

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#20]

**Comment by mathiascode** [comment]
I was thinking the IRC channel could be mentioned somewhere on the forum page, since discussions are made there.

**Comment by sphinxc0re** [comment]
The old website mentioned it

**Comment by mathiascode** [comment]
How does this look? http://final.cuberite.ga/discuss/

(I need to add an icon)

**Comment by bearbin** [comment]
`join us on IRC: #cuberite@irc.freenode.net` would seem to me to be a better wording, less quote marks.

**Comment by mathiascode** [comment]
Does it look better now? http://final.cuberite.ga/discuss/

**Comment by bearbin** [comment]
It looks fine to me.

On 28 October 2015 at 13:28, Mathias notifications@github.com wrote:

> Does it look better now? http://final.cuberite.ga/discuss/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cuberite/cuberite.github.io/issues/20#issuecomment-151844735
> .

## 

Alexander Harkness (bearbin)
Find my GPG key on the Ubuntu Keyserver - http://keyserver.ubuntu.com:11371/
Fingerprint: 93B3 D9D4 E65A CB47 BAF6 57AF 9537 B229 C1FD E7DF

**Comment by sphinxc0re** [comment]
You should leave the background as it is

**Comment by mathiascode** [comment]
Fixed in this PR, which is now merged: https://github.com/cuberite/cuberite.github.io/pull/23
