### ISSUE TITLE
Status of donations

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#21]
There has been some discussion about Gratipay being broken. Is there another place to make donations at currently, should the donation references be removed completely, or something else?

**Comment by sphinxc0re** [comment]
https://www.patreon.com/
https://www.bountysource.com/

**Comment by bearbin** [comment]
Patreon is focused on individual developers, not the project as a whole so would be unsuitable. 

Salt by bountysource would seem to be the way forwards.

**Comment by sphinxc0re** [comment]
For those, who don't know: https://salt.bountysource.com/

**Comment by madmaxoft** [comment]
We already had a team account on bountysource salt: https://salt.bountysource.com/teams/mc-server
Now I need to find out how to remove that, in favor of the new one.

**Comment by bearbin** [comment]
Acutally, I think that the new account I created is wrong too. We could have https://salt.bountysource.com/teams/cuberite as our name. I've submitted a claim so we can have access, but it might be another day or 2 before it is confirmed.

**Comment by sphinxc0re** [comment]
Nice! So we'll finally get some money (maybe) and _bountysource_ is kind of reliable.

**Comment by bearbin** [comment]
@xoft, I got the team renamed to the correct name. If you want to invite some more contributors we should start advertising it.

**Comment by sphinxc0re** [comment]
He actually meant @madmaxoft :D

**Comment by bearbin** [comment]
Derp, sorry. I need to remember usernames better :p

**Comment by madmaxoft** [comment]
@bearbin I think all of the people who regularly contribute to the server should be invited. However, I have no idea how to do that. The interface available to me doesn't seem to have any such function.

**Comment by madmaxoft** [comment]
Ah, found it. It is a rather unintuitive web.

**Comment by mathiascode** [comment]
So, donations will basically cover the web hosting fees?

**Comment by sphinxc0re** [comment]
Yeah, first of all. After all of them are covered, the rest will be split up equally

**Comment by bearbin** [comment]
@madmaxoft Could you move the money you are currently giving me for the buildserver over to bountysource, so

**Comment by bearbin** [comment]
Closing, bountysource is now available and linked to from the site.
