### ISSUE TITLE
Enlarge page contents

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#24]
The current size of the page content font is too small and really hard to read

**Comment by bearbin** [comment]
What page, or just overall?

What device are you using to view the site?

**Comment by sphinxc0re** [comment]
I mean the page contents except from the home page are too small.

**Comment by mathiascode** [comment]
Hm, how large is your screen? I might have to create some @media queries for larger screens as well.

**Comment by sphinxc0re** [comment]
25" full-hd

**Comment by mathiascode** [comment]
Understandable. My screen is 14". :P

I'll increase the font sizes for larger screens when I have time.

**Comment by sphinxc0re** [comment]
okay my home screen is like 27"

**Comment by mathiascode** [comment]
It's a laptop though.

Thanks for reporting these issues by the way. It helps a lot. :)

**Comment by sphinxc0re** [comment]
Well, thanks for housekeeping the website ;)

**Comment by mathiascode** [comment]
Progress :D

The page content will scale properly soon + there will be less and cleaner/better code.

**Comment by mathiascode** [comment]
Do the font sizes and UI element sizes look better to you now? http://final.cuberite.ga/

**Comment by sphinxc0re** [comment]
This looks really good. I think we can drop the download buttons on mobile devices, because we don't have any mobile builds yet

**Comment by sphinxc0re** [comment]
On the other pages (e.g. _support_) the text still looks a little too small on huge devices

**Comment by mathiascode** [comment]
I've added media queries up to 5100px now. Does the text look bigger?

**Comment by mathiascode** [comment]
I think hiding the download buttons will just cause more hassle. Maybe someone only has access to a device with a small screen at that moment, and wants to check the content of the archives, transfer the downloaded archive to a computer or something else.
