### ISSUE TITLE
Newsletter system

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#25]
How does the newsletter system work? Are newletters sent out automatically each week, or are they manually written? I registered my email address on October 27, but I haven't received any emails apart from the confirmation email.

**Comment by sphinxc0re** [comment]
ATM @bearbin and me aren't writing any newsletters. Me because I ain't got time for it. Same for @bearbin I guess. We were writing the letters manually. I don't think it is actually possible to generate them.

**Comment by bearbin** [comment]
The newsletters are written manually, and I've had a bit of a break from the project recently, so I haven't written any.

There haven't been that many major new features recently either, which would have warranted a special newsletter.

**Comment by sphinxc0re** [comment]
We should change the `1-2 a week` to `1-2 a month`

**Comment by bearbin** [comment]
Yes, we should. The only reason that it was initially set to 1-2 per week was to avoid irritating people if we did in fact put out that many emails. I'll do it in a few hours.

**Comment by sphinxc0re** [comment]
Okay, should we then carry on with our schedule? One month you, one month me?

**Comment by madmaxoft** [comment]
It would be great if all the newsletters could be archived on the web, so that they can be looked up later.

**Comment by sphinxc0re** [comment]
We could write the newsletter, send it out and post it on the blog

**Comment by bearbin** [comment]
@SphinxC0re Yes, that's what we were planning to do :)
