### ISSUE TITLE
Mention RaspberryPi

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite.github.io#28]
Many people are here for the Raspberry. Beginners reaching the [homepage](http://cuberite.org/) don't know that the proper raspberryPi download is "ARMv6". I think that the text should be modified to. `ARMv6 (Including Raspberry Pis)`, or something similar.

**Comment by bearbin** [comment]
ARMv6 may actually be an incorrect description for it - the executable will only actually run on RPi-compatible devices.
