### ISSUE TITLE
Manual is too far down

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite.github.io#32]
The manual should probably be on the top bar, and not the bottom one.

**Comment by mathiascode** [comment]
Maybe we could place a link below the download buttons? I'd prefer not to add it to the top bar, as a link to the user's manual already exists on the "Support" page.

**Comment by SafwatHalaby** [comment]
Yes, that would be good.
Perhaps a suitable spot is above the `Github Repository . Compile Cuberite` and below the Windows buttons.

**Comment by SafwatHalaby** [comment]
I still think the optimal spot is the top bar. For symmetry, you could also put the forums button there as well. Since that is important too.

**Comment by SafwatHalaby** [comment]
Either way, it's better than being down there.

**Comment by mathiascode** [comment]
A Forum button was added to the footer since one visitor wanted a direct link to the forum. The link to the forum is on the "Discuss" page, together with information about the IRC channel.

**Comment by SafwatHalaby** [comment]
The less clicks, the better. I'd replace the current `discuss` with `forums`, and the current `forums` with `IRC`. The exact same amount of buttons is kept. And IRC, being less important than the forum, moves down.

**Comment by SafwatHalaby** [comment]
What I'm saying is that "Discuss" is totally unneeded. Instead of having a discuss and a forum button, we could have a forum and an IRC button.

**Comment by SafwatHalaby** [comment]
Closing this and opening a more general issue.
