### ISSUE TITLE
Button arrangement

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite.github.io#34]
In my humble opinion, in order to maximize UX, the following buttons should be:
- Literally 1 click away.
- Visible without scrolling to footer.

The buttons are:
- Forum
- Manual
- Plugins
- The download buttons
- Contribute
- Compile

Currently, `Forum` and `Manual` do not meet the above criteria. I think this can be achieved by making the following changes:

**Top bar:**
Home, **Forum**, **Manual**, Plugins, Support, contribute (Removed Discuss, blog, added forum, manual)

**Just below the Windows download buttons:**
Compile Cuberite, Github Repo (Unchanged)

**Footer:** (These don't have to meet the above criteria since they are less important)
Donate, **IRC**, Newsletter, Api Docs, License (added IRC)

**Summary**
- Removed `discuss` and `blog`, creating two empty slots at the top bar.
- Moved `forum` and `manual` to the top bar, reoccupying the freed slots.
- Added `IRC` to the footer.
- Blog is unused anyways, its removal is fine.
- Discuss would become redundant once IRC is added to footer, its removal is fine.

Tell me what you think.

Edit: Mostly typos.
Edit2: Removed blog.

**Comment by SafwatHalaby** [comment]
There are probably several variations which also meet the criteria. Such as keeping the contribute on top and having 7 items on top. The exact ordering is not my point.

**Comment by bearbin** [comment]
I agree completely with this. I might even remove the blog, as it is useless at the moment.

**Comment by SafwatHalaby** [comment]
That would allow us to keep `contribute` on top while still having 6 buttons only.

Also, in the future `NewsLetter` could be renamed to `News`, and it would actually constitute the blog. People would either view it online or subscribe to it by mail.

**Comment by SafwatHalaby** [comment]
Updated original post according to @bearbin 's suggestion.

**Comment by mathiascode** [comment]
I agree with this as well. Something like this? http://final.cuberite.ga

**Comment by bearbin** [comment]
That looks better to me :)

**Comment by SafwatHalaby** [comment]
Much better!

**Comment by SafwatHalaby** [comment]
Note that when clicking "news letter", the footer changes.

**Comment by SafwatHalaby** [comment]
Maybe `news` should also be on the top bar?

**Comment by sphinxc0re** [comment]
@bearbin could we setup a system where we can post something on the blog and the newsletter is sent automatically?

**Comment by bearbin** [comment]
It would be quite easy for me to set up archives of the newsletter. I'll add that to my todo list.

**Comment by mathiascode** [comment]
Still working on this. I'll create a PR this weekend.

**Comment by SafwatHalaby** [comment]
Thank you :)

**Comment by SafwatHalaby** [comment]
Ping.
I don't mean to rush you, it's just that the changes have been already implemented at http://final.cuberite.ga since a long time, and I suspected that you might have simply forgot to PR.

**Comment by mathiascode** [comment]
I need to change the design of the "News" page as well, but there have been some other things that I wanted to work on instead. I'll fix this one as soon as possible, probably not in the next few days since it's Christmas.
