### ISSUE TITLE
Add actual Raspberry Pi logo

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#35]
[RPI_glyph.pdf](https://github.com/cuberite/cuberite.github.io/files/42881/RPI_glyph.pdf)

![rpi_glyph](https://cloud.githubusercontent.com/assets/3702016/11372356/475bf548-92cd-11e5-80cb-4628671227b0.png)

**Comment by sphinxc0re** [comment]
I have the svg if you like

**Comment by bearbin** [comment]
What is the copyright/trademark situation with this?

**Comment by SafwatHalaby** [comment]
Basically "Use freely as long as you don't deceive people and make them think they're buying stuff from the official Rpi foundation".

**Comment by sphinxc0re** [comment]
I got the original from wikimedia commons

**Comment by sphinxc0re** [comment]
then i made the glyph

**Comment by SafwatHalaby** [comment]
Reference: https://www.raspberrypi.org/trademark-rules/

Oh and:

> You may only use the Raspberry Pi Logo in connection with the sale or distribution of genuine Raspberry Pi products or services.
> If you use the Raspberry Pi Logo in this way on a website, the logo must link to our website at http://www.raspberrypi.org

**Comment by SafwatHalaby** [comment]
Another relevant part:

> Any use of the Raspberry Pi Marks must be accompanied by the acknowledgement “Raspberry Pi is a trademark of the Raspberry Pi Foundation”.

**Comment by bearbin** [comment]
So we can't use the logo then, according to the rules.

**Comment by sphinxc0re** [comment]
We can use the logo, as long as we follow the rules

**Comment by bearbin** [comment]
> 1. When can I use the Raspberry Pi Word Mark?
> 
> You may only use the Raspberry Pi Word Mark:
> 
> (ii) to state or indicate that another product is compatible with, works with or can be used with our products.
> 1. When can I use the Raspberry Pi Logo?
> 
> You may only use the Raspberry Pi Logo in connection with the sale or distribution of genuine Raspberry Pi products or services.

We can use the name "Raspberry Pi" but not the logo to indicate our compatibility.

**Comment by SafwatHalaby** [comment]
I think you mis-interpreted this. Why do you think we can't use the logo? We offer a genuine Raspberry Pi service.

**Comment by madmaxoft** [comment]
I'm more concerned about

> If you use the Raspberry Pi Logo in this way on a website, the logo must link to our website at http://www.raspberrypi.org

If I read that right, it means that the logo cannot be used on a download button, it can only point to their website.

**Comment by bearbin** [comment]
@SafwatHalaby My interpretation of a "genuine raspberry pi service" is a service provided by the raspberry pi foundation. It wouldn't make sense to me otherwise.

**Comment by SafwatHalaby** [comment]
Following that logic, you won't see any Rpi logo anywhere other than http://raspberrypi.org . But you do see them everywhere.

**Comment by tigerw** [comment]
I am of the firm opinion to err on the side of flagrant disregard for copyright.

**Comment by madmaxoft** [comment]
@tigerw After being bitten hard by the copyright "mafia", I tend to err on the side of safety.

**Comment by bearbin** [comment]
@tigerw Regardless of your disregard for copyright, trademarks are a much bigger issue. Trademark owners actually go after infringement for fear of losing their control over the mark. 

Notice how we changed from being `MCServer: A C++ Minecraft server` to being `Cuberite: A Minecraft-compatible game server`, which was in part to avoid infringement of Mojang's marks.

**Comment by tigerw** [comment]
I said it in a tongue-in-cheek way (does no one understand my jokes?) but:

That tends to happen with commercial products infringing on trademarks, right? I would imagine that it would be a bit of a PR disaster for the Rpi Foundation if an article on Reddit popped up saying Raspberry Pi Foundation files suit against open source project for using their logo on a download button or something to that effect.

No comment on the MCS vs Cuberite thing; I've said enough already :P
