### ISSUE TITLE
Add a banner to advertise the meetup

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#36]
> Okay, by the looks of it, the meeting will happen at the end of February from the 19th to the 21th. "Registrations" to the meetup are just for statistics, so that I can see how many of you will come: http://doodle.com/poll/ywaucxvcyzstt36z
> 
> The location is mentioned in the Doodle poll. It's a local hackerspace.

– taken from the forum

**Comment by sphinxc0re** [comment]
You could put it between the main title and the download section

**Comment by mathiascode** [comment]
This is on my todo-list. I'll probably put the banner underneath the navigation bar.

**Comment by sphinxc0re** [comment]
nice

**Comment by mathiascode** [comment]
Do you still want this banner inserted?

**Comment by sphinxc0re** [comment]
The meetup will still happen

**Comment by mathiascode** [comment]
Okay, I'll add a banner then

**Comment by mathiascode** [comment]
Have you written some kind of announcement about this?

**Comment by sphinxc0re** [comment]
I couldn't do that yet, because I don't have enough rights on the Forum. You can try to write something

**Comment by mathiascode** [comment]
I'll add a post to the "News" section of the site.

**Comment by sphinxc0re** [comment]
Okay

**Comment by mathiascode** [comment]
Something like this? http://final.cuberite.ga/news/cuberite-meetup/

**Comment by sphinxc0re** [comment]
Probably @bearbin should take a look at the grammar but so far it looks really good

**Comment by mathiascode** [comment]
Thanks!

**Comment by bearbin** [comment]
The announcement looks good. Two small fixes:

> on the meetup

should be `at the meetup`

> mark off the days you will be at the meetup

should be `mark off the days you are available to meet up`

**Comment by mathiascode** [comment]
Alright, I've corrected the mistakes. Thanks!

**Comment by sphinxc0re** [comment]
`Make sure to visit the Cuberite meetup`
@bearbin is that okay? What about
`Make sure to attend the Cuberite meetup` ?

**Comment by bearbin** [comment]
@SphinxC0re

Your suggestion is probably better.

**Comment by sphinxc0re** [comment]
Good. For the article, you should add the point that for those who can't come to the meetup, the whole thing will be streamed via an icecast service. Also every developer will be available on the TS3 and probably IRC.

**Comment by sphinxc0re** [comment]
I just talked to @bearbin and we both thought that it would be better to stream via YT/Twitch. I don't think we can do both, so we have to figure that out.

**Comment by mathiascode** [comment]
I fixed the error and added some information about streaming: http://final.cuberite.ga/news/cuberite-meetup/

**Comment by sphinxc0re** [comment]
What about a disclaimer? Could we get legal issues without one?

**Comment by mathiascode** [comment]
What kind of disclaimer?

**Comment by sphinxc0re** [comment]
A legal disclaimer?

**Comment by mathiascode** [comment]
I guess a privacy policy and cookie information is required, since we collect data from visitors

**Comment by sphinxc0re** [comment]
@bearbin does PIWIK have such a function?

**Comment by mathiascode** [comment]
What information about visitors do we collect at the moment?
