### ISSUE TITLE
Add FreeBSD builds

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#38]
I think at this point we have to overthink the website design. The main page will be totally cluttered if we add another two of those huge buttons. What about a download section instead?

**Comment by bearbin** [comment]
What about platform detection and a downloads page?

**Comment by sphinxc0re** [comment]
That would be great

**Comment by mathiascode** [comment]
Working on it.

**Comment by sphinxc0re** [comment]
Are you adding a whole download section? Because that would be better instead of just stuffing the whole frontpage with buttons

**Comment by mathiascode** [comment]
I was thinking about something like this: http://final.cuberite.ga/

What do you think?

**Comment by sphinxc0re** [comment]
Are you using any js for the dropdown?

**Comment by mathiascode** [comment]
It's pure HTML and CSS.

**Comment by sphinxc0re** [comment]
I love it :dancer:

**Comment by sphinxc0re** [comment]
Could you remove the transition of the menu buttons? I find it a somewhat bad UX

**Comment by mathiascode** [comment]
When you put your cursor over the buttons?

**Comment by sphinxc0re** [comment]
Yes

**Comment by mathiascode** [comment]
Alright, it's removed. http://final.cuberite.ga/
