### ISSUE TITLE
Create a privacy policy

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#42]
We should create a (simple) privacy policy that tells the user exactly what we do with the analytics information we collect and what we use cookies for. We could also insert a link to opt-out of Piwik's tracking (alternatively configure Piwik to respect the do-not-track feature in browsers). A link to this privacy policy could be placed in the footer.

Something similar to this perhaps? https://elementary.io/privacy-policy

**Comment by mathiascode** [comment]
How is this so far? http://final.cuberite.ga/privacy/

**Comment by sphinxc0re** [comment]
Looks good. We still need some grammar checking ;-) @bearbin

**Comment by mathiascode** [comment]
I extended the privacy policy a bit to cover the forum and newsletter.

**Comment by bearbin** [comment]
I didn't notice anything particularly wrong with the grammar, but

> while your email address is used only to send you an email about confirming your account.

I believe the forum also allows users to send emails to you. If I'm right, this should be updated.

I would also add a section to clarify that we do not currently track usage of the server binary itself.

**Comment by mathiascode** [comment]
Does it look better now?

**Comment by bearbin** [comment]
Lgtm

**Comment by sphinxc0re** [comment]
@mathias-github I think you can push this directly to the repo
