### ISSUE TITLE
Support E-mail

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite.github.io#43]
Last time I checked, the support E-mail was broken. If it is still broken, I suggest we remove it from http://cuberite.org/support/ until this is fixed.

**Comment by mathiascode** [comment]
Who is the maintainer of the email address?

**Comment by SafwatHalaby** [comment]
I think it's @bearbin. The email address is supposed to relay the message to several devs, including Tiger, Xoft, Sphinxc0re, me, and possibly others. But it wasn't reliably doing that last time I checked.

**Comment by bearbin** [comment]
@madmaxoft maintains the email address. I would be happy to take it on and get it working, but that would necessitate the transfer of the whole domain, which would be rather a lot of work and xoft probably doesn't want that.

**Comment by madmaxoft** [comment]
I wouldn't mind transferring the domain, I've just never done it before so I have no idea what needs to be done for that.

**Comment by bearbin** [comment]
@madmaxoft The process is quite simple, only a few things that need to be done.

First you need to "unlock" the domain in your registrar control panel. Then I can send a request to transfer and you can choose to accept.

A screenshot of the DNS control panel would be helpful also, so I can get everything working again after the transfer.

**Comment by bearbin** [comment]
Actually, it turns out that I also need a transfer code/EPP secret. If you could email that to me that would be good.

**Comment by SafwatHalaby** [comment]
Could we put a note that the mail is broken in the meantime?

**Comment by SafwatHalaby** [comment]
@mathias-github removed the e-mail in https://github.com/cuberite/cuberite.github.io/commit/aae9aa3a0cd3b5703c3b68a94ce19729aaff5126

**Comment by sphinxc0re** [comment]
This should stay open though, until we have a working mail service

**Comment by SafwatHalaby** [comment]
:+1:

**Comment by ghost** [comment]
@bearbin Can you add my email to dev??

Its alwaysonestepahead617@gmail.com

**Comment by mathiascode** [comment]
Should the email address be added back to the website?

**Comment by bearbin** [comment]
I think so, what other purpose would it have?

**Comment by mathiascode** [comment]
Is it fully functional now though?

**Comment by sphinxc0re** [comment]
Yes it is

**Comment by mathiascode** [comment]
Fixed in f5ef1eeb625aefce4d0821eed16e170f28f37ab1
