### ISSUE TITLE
Mirroring news

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite.github.io#44]
I think that every news announcement should be mirrored at the [forum announcement section](http://forum.mc-server.org/forumdisplay.php?fid=7) to encourage discussion. A link from the cuberite website to the relevant forum announcement would be nice.

**Comment by LogicParrot** [comment]
Mirroring at the forums is probably most easily done manually. Considering the low-volume nature of the news, that shouldn't be too hard.

**Comment by LogicParrot** [comment]
Mirroring at the forums is probably most easily done manually. Considering the low-volume nature of the news, that shouldn't be too hard. I am willing to take responsibility for that if I'm giving the proper forum permission.

**Comment by SafwatHalaby** [comment]
Mirroring at the forums is probably most easily done manually. Considering the low-volume nature of the news, that shouldn't be too hard. I am willing to take responsibility for that if I'm given the proper forum permission.

**Comment by SafwatHalaby** [comment]
It seems I already have the permission. I've submitted all of the news to the forum announcement section, but I didn't link to them from the main site.

**Comment by sphinxc0re** [comment]
@madmaxoft I would like to write announcements, too. Could you make me a moderator on the forums?

**Comment by SafwatHalaby** [comment]
@SphinxC0re Note that  the idea is to keep it in perfect sync with the homepage news. So we shouldn't "write announcements", I just wanted to sync the cuberite.org news with the forum announcements. Btw, who makes the newsletters?

**Comment by SafwatHalaby** [comment]
I want to give credit where credit is due, could anyone tell me who wrote each post?

**Comment by sphinxc0re** [comment]
@bearbin and I write the newsletter.

**Comment by SafwatHalaby** [comment]
To avoid misattribution to me, I'll write "Sphinxc0re and bearbin" on all of posts for now. PM me if you'd like to fine-grain this on a per-post basis.

**Comment by sphinxc0re** [comment]
@LogicParrot I'm sorry but you misspelled my name. It's **SphinxC0re** not **Sphinxc0re** :smile:

**Comment by SafwatHalaby** [comment]
@SphinxC0re Fixed.
