### ISSUE TITLE
Small color correction

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#48]
Could you remove the transparency from the dropdowns, but keep the darker grey?
I find the transparency kinda distractive.
![bildschirmfoto von 2016-02-04 19-29-06](https://cloud.githubusercontent.com/assets/3702016/12825267/c7c8f31c-cb75-11e5-9857-7318d4ca0271.png)
its #C3C3C3

**Comment by sphinxc0re** [comment]
Perfect! Thanks @mathias-github

**Comment by mathiascode** [comment]
:+1:
