### ISSUE TITLE
Moving the manual to this repository

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#49]
I suggest moving the user's manual to this repository, because
- It's easy to integrate it with the website design
- Better-looking URL on the main domain (http://cuberite.org/manual/)
- GitHub Pages CDN
- Markdown support

With the help of Jekyll, we can keep the file structure quite similar to the current user's manual: https://github.com/mathias-github/cuberite-redesign-final/tree/gh-pages/manual

The final site looks something like this: http://final.cuberite.ga/manual/ (it's unfinished, there is no specific CSS for the user's manual yet) (we could also enable multiple pages instead of one)

**Comment by bearbin** [comment]
I feel like this would be quite a lot of work for not much gain, seeing as what we have at the moment works. However, I would be willing to work on some of your pain points:
- Better Looking URL (by setting up a reverse-proxy in front of cuberite.org as is planned for HTTPS)
- Markdown Support (an hour of work in the genscript, not hard at all)

If you really feel the need to fix what isn't broken, then **please**, make sure to keep the following essential attributes in mind:
- Clean stylesheet optimised for readability above all else.
- Print stylesheet to allow printing directly from the page and producing an output at least as usable as at present.
- Single-page view is essential, multi-page is nice.

**Comment by SafwatHalaby** [comment]
~~@bearbin https is a good enough gain. A reverse proxy with https support which fetches stuff over the clear is just superficial https. The only way to get real https in book.cuberite.org is moving it out of the shared hosting server.~~

**Comment by bearbin** [comment]
?Sorry

book.cuberite.org currently has HTTPS, cuberite.org does not. The proposed way of adding HTTPS to cuberite.org was a reverse proxy.

**Comment by SafwatHalaby** [comment]
@bearbin I apologize! I assumed it does **not** have https.

**Comment by sphinxc0re** [comment]
I like the idea of changing the design to fit all of our other services. But the current genscript works fine

**Comment by mathiascode** [comment]
The system for this is ready. All I have to do now is to style the page, add a print stylesheet, and add the rest of the documentation.

**Comment by mathiascode** [comment]
How is it looking so far? This is roughly how the final style will be, once I've adjusted the spacing.
http://mathias-github.github.io/cuberite-redesign-final/manual/

Folder structure: https://github.com/mathias-github/cuberite-redesign-final/tree/gh-pages/manual

**Comment by mathiascode** [comment]
I think it's pretty much done now. Anything I should modify?

**Comment by SafwatHalaby** [comment]
Great job. :)

I have a few non essential remarks.
- I personally find it much easier to read long text on black on white/white-like and assume many others do. The old manual was easier for my eyes. I would appreciate a "switch to black on white" / "plain version" / "Printable version" button which turns things into B on W.
- The url color is too close to the background color, in my opinion, and I personally cannot find urls when skimming it.
- I wonder if you could also solve https://github.com/cuberite/users-manual/issues/38 if that's not too hard

Worth noting that your version closes https://github.com/cuberite/users-manual/issues/65

**Comment by bearbin** [comment]
I also agree with @LogicParrot. Black on White (well, black on some very light colour) should always be the default for reading. Aligning to the left also makes things much easier to read.

What I don't understand is why this is any better than the current site, in terms of either development or reading by users. What compelling reasons do you have for the change?

@LogicParrot How exactly does this fix cuberite/users-manual#65?

**Comment by mathiascode** [comment]
Is the readability better now?

I'd like to have as much of Cuberite's web things as possible in one place. It makes it easier to integrate with the website layout, and you just have to push changes once to make them apply everywhere.

Edit: I guess this could also be solved by adding HTML for the navigation bar and footer to the users-manual repository, and adding http://cuberite.org's stylesheet to http://book.cuberite.org. Does this sound better?

**Comment by bearbin** [comment]
Readability is much better now, but the links still need more contrast (and for me the text is a bit wide still). The title is a bit small also.

**Comment by mathiascode** [comment]
Is it better now?

**Comment by sphinxc0re** [comment]
Awesome! Good job 👍 How are we going to maintain the new manual? I'm thinking of creating a submodule for the actual manual, so we can update it and when we want to release it we can update the submodule inside the website repo

**Comment by bearbin** [comment]
I can't see any major issues with the new design. Since everybody else feels that it is such an upgrade over the current design, I would be inclined to copy over the CSS into the users-manual repository.

**Comment by sphinxc0re** [comment]
Why don't we move the manual to the website. We could shrink the server costs by moving as much to gh as possible

**Comment by SafwatHalaby** [comment]
I don't feel it's "such an upgrade", I'm just going with the flow and couldn't care less about this :P
I don't think we need submodule mess, just plain old PRs?

**Comment by bearbin** [comment]
No submodule mess - the book is not the website and it is not going to be in the website repository. It has it's own repository. I will change the style to the one @sphinxc0re + @mathias-github prefer, and add the header/footer. Hosting for the book costs no more than $0.5 per year, so that really isn't a worry.

**Comment by SafwatHalaby** [comment]
> @LogicParrot How exactly does this fix cuberite/users-manual#65?

Previously: https://book.cuberite.org/#2.4

Now: https://mathias-github.github.io/cuberite-redesign-final/manual/#worlds

The latter doesn't change with new versions. It can still change if we change the title, but that's rare.

**Comment by SafwatHalaby** [comment]
> I don't feel it's "such an upgrade", I'm just going with the flow and couldn't care less about this :P
> I don't think we need submodule mess, just plain old PRs?

I do really like the new css though.

**Comment by bearbin** [comment]
I can add additional links for the titles as well, without any difficulty.

**Comment by mathiascode** [comment]
https://github.com/cuberite/users-manual/pull/78
