### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite.github.io#50]
I was wondering if it would be possible to convert cuberite.org into https.
I know there's a technical difficulty since the site is actually hosted on Github and a cert would cause trouble. But it can be resolved:
- Have an nginx server serving the cuberite.org site, encrypt it with letsencrypt
- The server would proxy requests upstream to cuberite.github.io.
- The server has a ~5 minute page cache.

**Comment by bearbin** [comment]
The build server could do that, and it would be easy to set up over the weekend. 

I would need xoft to change the DNS though.

**Comment by SafwatHalaby** [comment]
Ok. Slightly off topic: I'm somewhat confused about the server topology. How many servers does the project have currently? And where is the new forum hosted?

**Comment by SafwatHalaby** [comment]
Oh, and the book too.

**Comment by bearbin** [comment]
I have no idea about the new forum.

We have the build server, the forum server, xoft's docs server, and the book + newsletter on shared hosting.

**Comment by bearbin** [comment]
I may have missed a few actually.

**Comment by SafwatHalaby** [comment]
Name: forum.cuberite.org
Address: 193.34.145.89

Name: builds.cuberite.org  
Address: 91.121.116.53

Name: book.cuberite.org
Address: 208.94.118.138

Name: api-docs.cuberite.org
Address: 217.16.187.16

**Comment by bearbin** [comment]
The book and newsletter are hosted on NearlyFreeSpeech.NET, the buildserver on Kimsufi, and the others IDK.

**Comment by mathiascode** [comment]
The new forum is hosted on SphinxC0re's VPS, and the API Docs on http://www.savana.cz/.

**Comment by sphinxc0re** [comment]
I'm hosting the forum at the moment

**Comment by mathiascode** [comment]
Any progress?

**Comment by bearbin** [comment]
@madmaxoft is working on transferring the domain I think, but there isn't an easy way from his host's control panel.

**Comment by LogicParrot** [comment]
Why is an ownership transfer needed? He'd just need to set the IP to direct to the buildserver.

**Comment by SafwatHalaby** [comment]
Why is an ownership transfer needed? He'd just need to set the IP to direct to the buildserver. (or wherever you're planning to host the reverse proxy)

**Comment by bearbin** [comment]
I think there was a reason, I can't remember what though. It would certainly be easier though.

**Comment by SafwatHalaby** [comment]
Perhaps it was the support E-mail setup.

**Comment by SafwatHalaby** [comment]
Yes, the transfer might be needed for #43, however, this issue can be resolved without a transfer.

**Comment by bearbin** [comment]
Yep, that was it. I can't do it right now, but I can set up the buildserver as a proxy over the weekend, and test it.

**Comment by ghost** [comment]
IF you want to USE SSL use https://letsencrypt.org/

**Comment by bearbin** [comment]
@alwaysontop617 That's what we're planning to do.

**Comment by ghost** [comment]
You will use lets encrypt?

If so, great.

**Comment by sphinxc0re** [comment]
We're already using _Let's Encrypt_ on most of our platforms. The webadmin and the website are the only platforms missing

**Comment by madmaxoft** [comment]
Would it be much trouble to host the actual main page somewhere else (perhaps at the build server?) and have it build the site from the GitHub repo whenever a new commit was pushed to it? Basically this would mean setting up the same engine that GitHub uses to generate the pages, plus a commit hook for the repo. Then we could drop the github redirection. I have a feeling that even the emails would start working then, I suspect they're not working because of the domain redirect at the top level.

**Comment by sphinxc0re** [comment]
Sounds like a very good idea. @bearbin?

**Comment by ghost** [comment]
Kk Why when I go to https://cuberite.org I see this:
![person-tree](https://cloud.githubusercontent.com/assets/17088079/13529080/b5fe61c8-e1df-11e5-8b1e-defc4013c4b1.jpg)
If you were using LetsEncrypt, I would not see this.
![soccer-ball](https://cloud.githubusercontent.com/assets/17088079/13529113/e5e7aa2a-e1df-11e5-8a77-a845bb804d4f.jpg)
Also the Certificate information says it is not LetsEncrypt but instead Github. I will create a script that automatically gives cuberite a valid ssl.

**Comment by mathiascode** [comment]
@alwaysontop617 HTTPS isn't set up yet.

**Comment by ghost** [comment]
https://gist.github.com/alwaysontop617/eeaaabd3f7330c08c7b7.

**Comment by ghost** [comment]
Ill work on it

**Comment by mathiascode** [comment]
The thing is, we need to move the site from Github first before we can set up Let's Encrypt.

**Comment by alwaysontop617** [comment]
KK Good News, I'll Host it

**Comment by ghost** [comment]
KK Good News, I'll Host it for you FREE, do you want me to host it?
![download](https://cloud.githubusercontent.com/assets/17088079/13529257/da8343dc-e1e0-11e5-9ba7-8131841b8c5c.jpg)
I would be glad to host it for you, who is the register for cuberite.org?

**Comment by madmaxoft** [comment]
Sorry, but we're not "giving away" our main assets to someone who just joined, no matter how enthusiastic they may be. We need someone whom we know is reliable and we can trust them. We already have a buildserver hosted, it should be possible to host the main page there as well.

**Comment by ghost** [comment]
Ok then, you will need to get a vps because let's encrypt is software and does not work with hosting, but if you decide to use my hosting service MSG me.

**Comment by bearbin** [comment]
@madmaxoft It is possible to set up a reverse-proxy for the main site there. I have set up a test of feasibility: https://crtest.bearbin.net

I would need to be online at the same time as you to do the domain redirection, to avoid downtime. All that we need is to change the CNAME record to point to the new server.

**Comment by mathiascode** [comment]
If possible, we should also enable HTTPS on the API Documentation site.

**Comment by ghost** [comment]
IK

On Fri, Mar 25, 2016 at 9:37 PM, Mathias notifications@github.com wrote:

> If possible, we should also enable HTTPS on the API Documentation site.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/cuberite/cuberite.github.io/issues/50#issuecomment-201682384

## 

Sincerely,
Thomas Wilbur

**Comment by SafwatHalaby** [comment]
Without this, by performing a MITM on the homepage, one could make clients download malicious executables by making the download buttons direct to the wrong site.

**Comment by tigerw** [comment]
Where can I buy this MITM® product? "Malicious Executables" sounds delicious.

**Comment by mathiascode** [comment]
Any updates on the DNS record modification (or domain transfer)?

**Comment by bearbin** [comment]
@mathias-github I asked @madmaxoft yesterday, he said he was on it.

**Comment by mathiascode** [comment]
Alright, thanks!

**Comment by mathiascode** [comment]
This is how we could solve the issue:
1. Update bearbin's reverse-proxy to point at http://cuberite.github.io
2. Remove the CNAME file in this repository
3. Change every mention of http://cuberite.org to https://cuberite.org in this repository
4. Update the main site's DNS record to point at the build server (where the reverse proxy is hosted)

It should be as simple as that. Bearbin already setup a reverse-proxy some time ago.

If someone is worried about SEO issues (duplicate content), that won't be an issue, since the website contains a canonical tag which ensures that all content on cuberite.github.io will be indexed as cuberite.org.

**Comment by bearbin** [comment]
Yes, it's very easy to do. But I am waiting until the domain name is transferred, and xofts registrar is being terrible at actually allowing the transfer to complete.

**Comment by sphinxc0re** [comment]
We are able to activate ssl on GH pages, aren't we. We are also able to set a custom domain name in the settings

**Comment by bearbin** [comment]
No, GH pages do not yet support HTTPS with a custom domain.

**Comment by mathiascode** [comment]
A recent change by Github: When the CNAME file is removed, it is possible to enforce HTTPS on cuberite.github.io. The option is available in the settings of this repo.

No support for custom domains though, so we still have to use the reverse proxy method.

**Comment by madmaxoft** [comment]
I think I'd prefer a real web server running HTTPS on the cuberite.org domain, rather than a proxy.

At least if I understand correctly, the proxy works by providing HTTPS access to another HTTP server, so when the browser makes an HTTPS request to the proxy, it makes a request on behalf of the browser to the original HTTP server - but there's no protection there, anyone can attack this plain connection. This sounds very dangerous to me, because we'd basically be hiding potential malicious attack surface behind our own cert and we'll pretend that it's secure, when in fact it is not.

**Comment by bearbin** [comment]
The proxy would be connecting to the GitHub server over HTTPS so it would be secure.

**Comment by tigerw** [comment]
Since we're talking about proxies, here's an even easier way (with no dependency on bearbin :P): https://kloudsec.com/github-pages/new

**Comment by madmaxoft** [comment]
So you run it through a third party who see all of people's traffic. NSA must be really happy about such a service :P

**Comment by SafwatHalaby** [comment]
> I think I'd prefer a real web server running HTTPS on the cuberite.org domain, rather than a proxy.

The site uses Jekyll. It should be simple to setup a real web server which fetches the repo every once in a while, runs Jekyll to generate the static content, and serves it. It's only slightly harder than the reverse proxy method, I think.

**Comment by tigerw** [comment]
> So you run it through a third party who see all of people's traffic. NSA must be really happy about such a service :P

If the NSA starts intercepting traffic, it should be a cause for celebration! It must mean we're getting really popular.

**Comment by sphinxc0re** [comment]
The website is really well protected from downtime because we're not hosting it ourselves. I'm fine with @tigerw's solution, so let's use kloudsec

**Comment by bearbin** [comment]
I would much rather not use kloudsec. Ignoring security for the time being (although that is a major consideration), one has to consider the increased downtime caused by the system, the possibility of it going away (very likely for a free service), and a lack of configurability as to what options we want.

**Comment by SafwatHalaby** [comment]
> it makes a request on behalf of the browser to the original HTTP server - but there's no protection there, anyone can attack this plain connection.

As Bearbin already mentioned, our server would connect to the Github server over a secure connection. It's a hack; The browser cannot connect securely to Github via the `cuberite.org` domain because of a cert mismatch. So it connects to us securely, and we send it the cached Github page.

> I think I'd prefer a real web server running HTTPS on the cuberite.org domain, rather than a proxy.

Note that a proxy with a long cache is effectively a real web server. If 1000 users connect in an instant, only 1 request will be made upstream to Github. No further upstream requests would be made till the cache times out, and then another 1 request would be made.

**Comment by tigerw** [comment]
If you're talking about downtime, well, does bearbin provide availability guarantees? Without getting into yet another disagreement, companies do have better teams compared to individual people, generally.

**Comment by SafwatHalaby** [comment]
The buildserver has an excellent track record though. Is Bearbin's server availability a real concern? It's practically 100%, is it not?

**Comment by bearbin** [comment]
@tigerw I would in fact argue the opposite - as you get larger reliability decreases. It is only the extraordinarily large providers who have excellent uptime. More infrastructure, more layers, more complexity, all cause more downtime unless you have a team of 20 SREs working around the clock.

It's not a major issue in the scheme of things though, more the stress of it disappearing one day and having to change everything over, with no notice. (which tends to happen for things you don't pay with aquihires etc)

**Comment by tigerw** [comment]
...what if bearbin disappears one day..? He does have the keys to the kingdom, so to speak.

:D

ANYWAYS, as I said, just a thought.

**Comment by SafwatHalaby** [comment]
> ...what if bearbin disappears one day.

Lol. I suppose that's a problem anyways. The disappearance of the DNS holder would be a problem, Kloudsec or not.

**Comment by bearbin** [comment]
The domain is finally transferred. HTTPS should be up tomorrow.

**Comment by bearbin** [comment]
HTTPS is now completed. Test it out :)

**Comment by mathiascode** [comment]
Thanks!

Can you enforce HTTPS on cuberite.github.io just in case? There's an option in the repository settings.

**Comment by bearbin** [comment]
@mathias-github done.

**Comment by SafwatHalaby** [comment]
Which method was used, eventually? If it's the proxy method, you should make sure caching is working as expected to minimize latency.

**Comment by bearbin** [comment]
The proxy method was done, but I haven't enabled caching yet. I will do that soon.

**Comment by SafwatHalaby** [comment]
Alright. Enabling caching with nginx should be a rather trivial config change.

**Comment by bearbin** [comment]
I enabled caching yesterday, but I didn't notice any difference in response time, still a very reasonable 320ms (time to last byte for homepage HTML) for me.

**Comment by bearbin** [comment]
@LogicParrot Caching is verified enabled, is it all good now?

**Comment by SafwatHalaby** [comment]
We can undoubtably tell that the cache is working by doing this:
- Set a reasonable cache time (e.g. 5 - 60 minutes).
- Visit cuberite.org
- Push a commit immediately afterwards, changing a page we visited.
- See if the change appears immediately or not.

**Comment by bearbin** [comment]
@LogicParrot It is working, I enabled the debug messages and tested.

**Comment by mathiascode** [comment]
We made the right choice. https://kloudsec.com is offline, and the certificate on https://blog.kloudsec.com/ expired on July 27.

Edit: Yes, it shut down. https://www.reddit.com/r/webdev/comments/4s3kmf/got_an_email_saying_that_kloudsec_will_be/

**Comment by bearbin** [comment]
LOL. I guess so.
