### ISSUE TITLE
Alter banner for the beginning of the meetup; Add a post to announce the start; Add Twitch

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#53]
The twitch.tv address is simply:
https://twitch.tv/cuberite

The post should go out tonight

**Comment by mathiascode** [comment]
Something like this? http://final.cuberite.ga/news/start-of-the-cuberite-meetup/

**Comment by sphinxc0re** [comment]
Looks good! Merge it in!

**Comment by mathiascode** [comment]
Alright, done
