### ISSUE TITLE
Add links to social media pages

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#54]
Any pages other than YouTube and Twitter?

**Comment by bearbin** [comment]
Google+ is https://plus.google.com/b/115692611616794030769/115692611616794030769
Twitter is https://twitter.com/cuberiteproject
YouTube is https://www.youtube.com/channel/UC0eyU42IIkUoJ_h5Oj5fi-A

BountySource? https://www.bountysource.com/teams/cuberite
IRC?

**Comment by SafwatHalaby** [comment]
CuberiteDiaries is "non-official" as of now, so I'm not sure it belongs. Just thought I'd mention it:
https://vimeo.com/cuberite

**Comment by sphinxc0re** [comment]
Twitch?

**Comment by mathiascode** [comment]
Thanks for the info!

**Comment by mathiascode** [comment]
How does this look? http://final.cuberite.ga/

**Comment by bearbin** [comment]
Looks good, apart from that the G+ logo is wrong.

**Comment by mathiascode** [comment]
I'll change it.

What do you think, should the Twitch link be there or not? It feels a bit strange to redirect visitors to a page that's rarely used. When we use Twitch, there will most likely be a news post about it.

**Comment by sphinxc0re** [comment]
We should enable the twitch logo, when used and highlight it then

**Comment by mathiascode** [comment]
I've updated the Google+ icon.

**Comment by bearbin** [comment]
I'm happy with it now, are you @SphinxC0re?

**Comment by sphinxc0re** [comment]
I'm not too happy with the twitch icon. Like I said, we should only show it when we actually make use of twitch

**Comment by mathiascode** [comment]
I've removed the Twitch icon now. The CSS code for it will still be there for the future.

**Comment by bearbin** [comment]
Great, merge it in :)
