### ISSUE TITLE
G+ and twitter icons not shown on smaller screens

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#60]
I'm usually working on a 14.5 inch screen. This is the result for the bottom right corner:
![auswahl_028](https://cloud.githubusercontent.com/assets/3702016/14368033/82557e40-fd1b-11e5-9c72-f37464238d90.png)

**Comment by mathiascode** [comment]
Which browser and operating system? I haven't noticed this on my 14 inch screen.

**Comment by sphinxc0re** [comment]
Arch Linux  on both Firefox and Chromium.

**Comment by mathiascode** [comment]
Do you have some kind of addon that removes social buttons? The Twitter and Google+ buttons disappeared when I added Fanboy's Social Blocking List to Adblock Plus.

**Comment by mathiascode** [comment]
Can you see the links here? http://mathias-github.github.io/cuberite-redesign-final/

**Comment by sphinxc0re** [comment]
I can already see them in production. It seems like you've already fixed the issue
