### ISSUE TITLE
Important content below the fold.

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite.github.io#62]
![selection_001](https://cloud.githubusercontent.com/assets/1297699/14587759/75cd51ce-04b0-11e6-9ee5-538958f0793a.png)

There is more than enough space on my 1080p screen to have the benefits and bottom bar above the fold, and having them below is bad for user experience.

**Comment by mathiascode** [comment]
How does this look? http://mathias-github.github.io/cuberite-redesign-final/

**Comment by bearbin** [comment]
It's better, although the footer still isn't visible.

**Comment by mathiascode** [comment]
How much of the footer is outside the screen?

**Comment by bearbin** [comment]
All of it for me: 
![selection_002](https://cloud.githubusercontent.com/assets/1297699/14588025/0b38cf44-04b7-11e6-916e-32030aa665f6.png)

**Comment by SafwatHalaby** [comment]
The footer is also not visible on my laptop, it has always been that way. On mobile it's even worse; You scroll down, down, down, and there's a menu button down there, and it isn't obvious that this menu button has a different menu than the upper menu button.

**Comment by mathiascode** [comment]
I'll play around with the front page design a bit to see what works the best.

**Comment by mathiascode** [comment]
I'll work on this issue in the beginning of June. Too many things to do this month.

**Comment by mathiascode** [comment]
I took a little break from Cuberite last month, but I've started working on this issue again.

**Comment by mathiascode** [comment]
What if we remove the benefits bar, and change the tagline to something that points out the benefits of the server?

E.g. "A lightweight, fast and extensible game server for Minecraft"

The visitor can click on the "About" link in the footer to learn more about Cuberite (server written in C++, plugins in Lua, history etc).

http://mathias-github.github.io/cuberite-redesign-final/

**Comment by bearbin** [comment]
That looks good to me :)

**Comment by SphinxC0re** [comment]
![bildschirmfoto 2016-07-03 um 20 51 45](https://cloud.githubusercontent.com/assets/3702016/16547063/fa7ad1f8-415f-11e6-8faa-f0a7f3825ad8.png)
![bildschirmfoto 2016-07-03 um 20 52 30](https://cloud.githubusercontent.com/assets/3702016/16547064/15d2413e-4160-11e6-882a-4840cbd8747d.png)

Seems like there is something wrong with the layout. Other than that, I find this a really good idea 😄

**Comment by sphinxc0re** [comment]
I think it would be better to discuss the tagline on the Forum. I really like the new proposal

**Comment by sphinxc0re** [comment]
Could you also make the background a little bit brighter? It's really difficult for the eyes at the moment

**Comment by mathiascode** [comment]
Better now?

**Comment by sphinxc0re** [comment]
Could you try this as the "white" on the website: #eaeaea
Also could you try to bring the background to nearly this color: #1e1e1e

Just a test

**Comment by mathiascode** [comment]
Done.

**Comment by mathiascode** [comment]
Can you see a background pattern on your screen?

**Comment by sphinxc0re** [comment]
Yes 👍 
You just have to adjust the bottom icons in mobile mode

**Comment by madmaxoft** [comment]
It looks quite weird on small computer screens, and the More menu item is garbled:
![web_small](https://cloud.githubusercontent.com/assets/4388386/16548144/db89b644-4185-11e6-999d-a6448d47540c.png)

**Comment by mathiascode** [comment]
There's still a few things I need to change before it's ready.

**Comment by sphinxc0re** [comment]
For those of you, which aren't that 'scroll-hungry' : http://mathias-github.github.io/cuberite-redesign-final/
😉

**Comment by madmaxoft** [comment]
The Windows download seems to have a Linux icon :P

**Comment by sphinxc0re** [comment]
<img width="274" alt="bildschirmfoto 2016-07-06 um 09 50 21" src="https://cloud.githubusercontent.com/assets/3702016/16610994/1cbb97e2-435f-11e6-8a3d-0662a5d7e8e2.png">

**Comment by sphinxc0re** [comment]
I am really excited for more updates. @mathias-github?

**Comment by mathiascode** [comment]
I'm back home again, so I hope to get an update out as soon as possible.

**Comment by sphinxc0re** [comment]
👍

**Comment by mathiascode** [comment]
I'm not dead. :O

Some progress at least. http://mathias-github.github.io/cuberite-redesign-final/

**Comment by bearbin** [comment]
It looks great! Simple, but all the information is there.

**Comment by mathiascode** [comment]
Good to hear that. How is this support page? http://mathias-github.github.io/cuberite-redesign-final/support/

**Comment by bearbin** [comment]
The button in the forum section has the wrong text and link.

The IRC button text should be replaced with chat.freenode.net / #cuberite IMO (any other opinions here?)

Also, is there any advantage of kiwiirc over the freenode webchat?

**Comment by mathiascode** [comment]
I've fixed the forum link.

Last time I checked (summer last year), kiwiirc worked better on mobile phones than freenode webchat, but I think freenode has made their webchat responsive after that. I could change the link if you want me to.

**Comment by mathiascode** [comment]
I made the subscribe-section on the news page a bit more descriptive: http://mathias-github.github.io/cuberite-redesign-final/news/#subscribe

**Comment by bearbin** [comment]
#cuberite isn't useful on it's own, there needs to be a mention of freenode somewhere.

The subscribe-section seems good for me.

I would also be in favour of replacing "Support Forum" with a CTA-style button - "Join the Forum", "Visit Forum", similar to the email button.

**Comment by mathiascode** [comment]
I've updated these now. The icons have also been corrected. Anything else that I should change?

**Comment by bearbin** [comment]
LGTM

**Comment by mathiascode** [comment]
Alright. I'll push the changes to this repository.

**Comment by mathiascode** [comment]
Fixed in f5ef1eeb625aefce4d0821eed16e170f28f37ab1
