### ISSUE TITLE
Remove "1.7" from the homepage

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#63]
I think we should keep support for 1.7 for now, but don't tell new visitors that we support it. Cuberite is very unstable in 1.7 at this point (new 1.8 mobs cause client crashes on first join, right clicking/placing blocks doesn't work etc.).

**Comment by sphinxc0re** [comment]
I though about dropping 1.7 as well. Since e can always suppport two versions of the protocol, that might be good idea
