### ISSUE TITLE
Add "getting started" tips after downloading Cuberite

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#64]
When a new visitor downloads Cuberite, there should be an obvious link to a "Getting started" guide (the manual).

I plan on adding an on-page popup, that appears when a visitor clicks on a download link. This popup will contain a link to the manual, and some text which explains that downloads on the front page update quite often.

**Comment by sphinxc0re** [comment]
Will you be able to solve this using only css?

**Comment by mathiascode** [comment]
Yes, that should be possible.

**Comment by sphinxc0re** [comment]
Them I'm all for it

**Comment by mathiascode** [comment]
I've not been able to accomplish this without Javascript, but I added a link underneath the download buttons which contains "getting started"-information. The text is not final yet.
http://mathias-github.github.io/cuberite-redesign-final/

**Comment by mathiascode** [comment]
Fixed in f5ef1eeb625aefce4d0821eed16e170f28f37ab1
