### ISSUE TITLE
HTTPS on API docs

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#67]
Currently we have HTTPS activated on all of our domains except for the API docs. We should activate HTTPS on there at some point.

**Comment by madmaxoft** [comment]
Those are still hosted by me, and https is unavailable at my webhost.
If we moved them, we'd need to re-set-up the update scripts.

**Comment by mathiascode** [comment]
Seems to be fixed.

**Comment by bearbin** [comment]
I set up a reverse proxy from my server as @madmaxoft's hosting broke the system and HTTPS was added in the process (although with an insecure backend connection).
