### ISSUE TITLE
Download button hovering problems

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite.github.io#68]
Something is wrong with the download buttons.
When hovering over a download button, a menu appears with 32/64 bit choices.
When moving the mouse down to click one of those choices, the menu disappers.

This does not always happen, it happens when you move past a certain speed. My hypothesis there's a "dead area" between e.g. the  "Linux" button and the "32 bit" button, and hovering over that dead area hides the menu, but moving the mouse fast enough skips that dead area.

**Comment by mathiascode** [comment]
Which browser are you using?

**Comment by mathiascode** [comment]
I moved the dropdown menu 1 px up. Does the problem still occur?
Demo: http://mathias-github.github.io/cuberite-redesign-final/

**Comment by SafwatHalaby** [comment]
The problem no longer occurs. I was using Firefox 45.2

**Comment by mathiascode** [comment]
Great! Fixed in ac9c2ceea67d61a3f593a052d8c5181b082a65ab

**Comment by SafwatHalaby** [comment]
:)
