### ISSUE TITLE
Add testing builds to the homepage.

### ISSUE THREAD

**Issue by worktycho** [cuberite/cuberite.github.io#7]

**Comment by bearbin** [comment]
ARM testing builds will have to come soon as well. 

I am running into a little bit of an issue with disk space, I may have to upgrade the system to a better VPS soon to add them.

**Comment by mathiascode** [comment]
Closing this issue for now, since our approach for testing builds isn't working well at the moment.
https://forum.cuberite.org/thread-2419.html
