### ISSUE TITLE
Wrong redirect

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#70]
http://www.cuberite.org redirects to https://cuberite.org as it should, but https://www.cuberite.org/ redirects to https://raw.githubusercontent.com/cuberite/cuberite/master/compile.sh.

**Comment by bearbin** [comment]
It's most likely I simply hadn't got around to setting up www.cuberite.org completely yet. Does it not give a HTTPS error?

**Comment by bearbin** [comment]
I'll add it to my todo list anyway.

**Comment by bearbin** [comment]
Fixed.
