### ISSUE TITLE
Make color scheme more colorful and brighter for better readablity

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#72]

**Comment by mathiascode** [comment]
Which color(s) should be used?

**Comment by sphinxc0re** [comment]
Good question 😁 I'm not really a designer. Knock yourself out and present me some color Presets if you like

**Comment by tigerw** [comment]
How about...<https://en.wikipedia.org/wiki/Black_and_Yellow>

Sent from Windows Mail

**Comment by sphinxc0re** [comment]
I wouldn't like the standard *Minecrafty* looks with *brown* and _green_.

**Comment by mathiascode** [comment]
How is something like this? http://mathiascode.github.io/cuberite-website-changes/

**Comment by sphinxc0re** [comment]
:nauseated_face: not so good. But I'm also not sure what kind of color palette we should choose

**Comment by sphinxc0re** [comment]
https://color.adobe.com
I think you should choose a complementary palette

**Comment by mathiascode** [comment]
This is my weak side. Let me try some other palettes.

**Comment by mathiascode** [comment]
How are the colors now?

**Comment by sphinxc0re** [comment]
I asked a designer at work to do the coloring 😉 no offense, you did a really good job in every other aspect of the website

**Comment by mathiascode** [comment]
Thanks, but what's wrong with the current colors? I'd like some feedback, so that I can improve.

**Comment by bearbin** [comment]
The current website colours are fine, except that they are light-on-dark which is not so good for readability on most monitors. The proposed new colours are bad, because they don't go with each other and they are completely different from the cuberite colour scheme. Personally, my choice would be to flip dark with light on the current site until it looks readable enough, but then again I'm not a proper designer myself.

**Comment by mathiascode** [comment]
That's basically the manual right now.

**Comment by tigerw** [comment]
I think everyone is nitpicking.

Before the fancy colour monitors, guess what we considered to be a

![grayscale](http://www.topdesignmag.com/wp-content/uploads/2011/07/03_design-by-newconcept.jpg)

**website?**

That's right—grayscale.

Maybe with just a small splash of colour.

**Comment by tigerw** [comment]
And of course, for true accessibility, you could use the User's Choice (Awards 2016): [Their chosen system colours!](http://www.iangraham.org/books/xhtml1/appd/update-23feb2000.html)

After all, everyone knows that the user knows best.

**Comment by mathiascode** [comment]
We need to come to an agreement. Should we use the current color scheme, perhaps with a lighter background for better readability and a bit of color, or should we change the color scheme completely?

It's becoming annoying to slightly change the colors every now and then. If we can settle with something that most people are happy about, that would be great. So far, it seems like more people want colors similar to the current ones.

**Comment by madmaxoft** [comment]
Speaking as a somewhat blind person, I'd really prefer to have a dark text on light background on the main page, but I don't really care that much - I haven't actually seen the main page for what feels like centuries, so whatever goats your float :)

**Comment by sphinxc0re** [comment]
I would like to wait on my designers opinion first, if you guys don't mind. She really knows her stuff

**Comment by sphinxc0re** [comment]
How about this color scheme: https://cuberite-plugin-registry.herokuapp.com/

**Comment by mathiascode** [comment]
Would this color cover the whole background on pages with text too? I'd prefer a more muted color.

**Comment by SafwatHalaby** [comment]
https://book.cuberite.org/ looks pretty.

**Comment by mathiascode** [comment]
Do you still want this change?

**Comment by sphinxc0re** [comment]
I'm not sure anymore. I guess we can close this for now.
