### ISSUE TITLE
Keep IRC link or not

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#76]
Should we keep promoting the IRC channel in the website footer? Every now and then a new user asks a question there, but doesn't receive an answer since devs don't use IRC very often.

**Comment by madmaxoft** [comment]
If it were up to me, I'd remove it :)

**Comment by bearbin** [comment]
If it were up to me, I'd keep it :)

We have the forum which is promoted much more heavily - removing the IRC isn't going to make people notice the forum link.

**Comment by madmaxoft** [comment]
It would make those, who currently go to irc and get no reply, go to the forum instead and receive a proper response.
