### ISSUE TITLE
Make background more noisy

### ISSUE THREAD

**Issue by sphinxc0re** [cuberite/cuberite.github.io#77]
I thought of something like this: https://www.toptal.com/designers/subtlepatterns/dark-sharp-edges/
I guess @mathiascode could do that using only css?

**Comment by mathiascode** [comment]
What do you think about a gradient similar to https://uigradients.com/? One short line of CSS (e.g. background: linear-gradient(to top, color1, color2) fixed;)

Example: https://mathiascode.github.io/cuberite-website-changes/

**Comment by sphinxc0re** [comment]
@mathiascode I love it. For real. Did you take a look at the mobile version though? The colors on desktop are amazing but don't seem right on mobile

**Comment by mathiascode** [comment]
The colors are the same on the desktop and mobile version, but they could vary on different screens. What kind of screen do you have?

Edit: I tweaked the gradients a little and added some transparency on the navigation bar and footer on the mobile version's home page. Does it look better?

**Comment by sphinxc0re** [comment]
I think transparency is not that good but I also think from now on it's more about taste than anything else. I would personally prefer a opaque top bar.

**Comment by mathiascode** [comment]
I can agree on that. Makes it a little hard to read. Reverted the change.

**Comment by bearbin** [comment]
Also, I found this tool for checking contrast ratios of different colours. I think we should aim to at least pass the WCAG AA standard.

**Comment by mathiascode** [comment]
The colors are WCAG AA compliant at the moment.

**Comment by madmaxoft** [comment]
The background is too light, when compared to the white font. It is somewhat painful to read.

**Comment by mathiascode** [comment]
Is it better now?

**Comment by madmaxoft** [comment]
Yes, that's better.

**Comment by sphinxc0re** [comment]
@mathiascode  is it posible to hide all downloads except the android one on mobile?

**Comment by mathiascode** [comment]
We could probably display the download button for Android immediately on smaller screens, and add a small link that shows the rest of the download buttons when clicked on.

**Comment by sphinxc0re** [comment]
That would be even nicer

**Comment by mathiascode** [comment]
I added a "show more" link. Does it work fine for you? I'll fix the spacing and style of the button link.

**Comment by sphinxc0re** [comment]
👍  Love it. How about @cuberite/core-team ?

**Comment by madmaxoft** [comment]
Although not relevant to this issue, I like it.

**Comment by sphinxc0re** [comment]
Yeah, the discussion about the websites UX kinda moved here 😜

**Comment by mathiascode** [comment]
The toggle button is done

**Comment by mathiascode** [comment]
Anything else I should change?

**Comment by mathiascode** [comment]
Here's the new icon:
![icon](https://cloud.githubusercontent.com/assets/8754153/25178356/2ceedd36-250e-11e7-8e74-fd96cab3c4bc.png)

SVG: https://mathiascode.github.io/cuberite-website-changes/brand/icons/white_background.svg

**Comment by madmaxoft** [comment]
I like the icon with the gradient, it would be great for the favicon, too. Right now the favicon's too similar to github (and 9gag and others), we need something more unique. This could be it :)

**Comment by mathiascode** [comment]
Alright, I changed the favicon. :)

**Comment by ItsShadowCone** [comment]
Imo the colors just don't fit to the white as good as the black one (or not quite black one)
