### ISSUE TITLE
The build status images don't show in Firefox nightly

### ISSUE THREAD

**Issue by Bond-009** [cuberite/cuberite.github.io#79]
https://screenshots.firefoxusercontent.com/images/fdeb037a-eb81-493c-bb4d-236bfad7e326.png

**Comment by bearbin** [comment]
How odd, they show for me using firefox.

Can you try loading the images on their own using the URL in the source?

**Comment by Bond-009** [comment]
They work when I view them from there source URL.

Maybe this is a Firefox nightly issue, but they show up properly on GitHub.

**Comment by madmaxoft** [comment]
Where is that page located? I can't find it.

**Comment by Bond-009** [comment]
AFAIK there are no links on the site to it: https://cuberite.org/status

**Comment by mathiascode** [comment]
I'll look closer into this. The badges load very slowly overall.

**Comment by williamhatcher** [comment]
@Bond-009 makes a great point. I'll add a link in the footer later.

**Comment by mathiascode** [comment]
Just to confirm if this is a temporary issue or not, do the images still not show up?

**Comment by SafwatHalaby** [comment]
I can see the images on Firefox.

**Comment by Bond-009** [comment]
I still can't see them on Firefox nightly, but they show up an GitHub and Travis

**Comment by bearbin** [comment]
Can you check in your developer tools/network requests area and check if any errors appear?

**Comment by Bond-009** [comment]
Everything seems fine in the network tab, but when I hover my mouse over the image source in the inspector, it says: "Could not load the image"

**Comment by Bond-009** [comment]
Fixed in Firefox Nightly 58 ¯\_(ツ)_/¯
