### ISSUE TITLE
Newsletter registration confirmation page needs styling

### ISSUE THREAD

**Issue by williamhatcher** [cuberite/cuberite.github.io#83]
https://newsletter.cuberite.org/subscribe.php

Should be styled like the rest of the site.

And should include an error if there is an invalid email in the POST.

**Comment by bearbin** [comment]
Unfortunately last month the email verification service I was using was taken down and the newsletter has no email verification system at present. I am working on adding a new system.

The newsletter is not part of the main site, and a confirmatin page doesn't need any fancy styling really - the user is going to click away the next second in any case.

**Comment by bearbin** [comment]
Closing this issue as the newsletter is not the main site.

**Comment by bearbin** [comment]
As an update, the invalid email message has been fixed - a new solution has been found.

**Comment by williamhatcher** [comment]
You can easily test if `$_POST['email]` exists and whether or not it is a valid email.

Was not sure where to put this issue.
