### ISSUE TITLE
Add underlines back to hyperlinks

### ISSUE THREAD

**Issue by bearbin** [cuberite/cuberite.github.io#84]
Example here: https://bearbin.github.io/cuberite.github.io/

For usability's sake, there is no real reason to remove the underlines from links, except when they are obviously links from context (buttons and navigation).

**Comment by Bond-009** [comment]
I find it way better-looking without.

**Comment by mathiascode** [comment]
The blue and bold links are differentiated enough in my opinion. Underlines look a bit too noisy.
