### ISSUE TITLE
Feature request: Notice template

### ISSUE THREAD

**Issue by SafwatHalaby** [cuberite/cuberite.github.io#86]
Sometimes we need to issue quick homepage notices. The CSS is already there, but I think we need a template for convenience. The idea is filling an .md file with the notice text, and that would make it appear on the homepage. Blanking the file removes the notice. 

Reference: https://github.com/cuberite/cuberite.github.io/commit/8ed1360d7c245dd335f5617458021b959ce0c331

**Comment by mathiascode** [comment]
Implemented in 60ea7708aa57e8a3dc8644d9be41ec39eac2f347
