### ISSUE TITLE
error when downloading plugins

### ISSUE THREAD

**Issue by misaalanshori** [cuberite/cuberite.github.io#88]
I'm getting this error: 
ERROR: Unable to connect to MySQL server! Error: Access denied for user 'bde5006a4f0235'@'104.41.1.8' (using password: YES)
when trying to download any plugin from https://plugins.cuberite.org
![image](https://user-images.githubusercontent.com/38964181/44350416-887bda00-a4c9-11e8-90f4-f9d3656b0d2d.png)

**Comment by bearbin** [comment]
Thank you for reporting this issue. It is being dealt with in the relevant repository, hopefully @tigerw is able to fix it. https://github.com/cuberite/plugin-repository/issues/44
