### ISSUE TITLE
Search SQL Failure

### ISSUE THREAD

**Issue by sfxworks** [cuberite/cuberite.github.io#89]
When trying to search for "web" (looking for a dashboard plugin) I get the following error.

`ERROR: Unable to connect to MySQL server! Error: Access denied for user 'bde5006a4f0235'@'104.41.1.8' (using password: YES)`

**Comment by sfxworks** [comment]
Issue still remains, but on a related note I found you all already have one :D 

https://book.cuberite.org/#2.3

**Comment by bearbin** [comment]
Closing as duplicate of cuberite/cuberite#4305. Sorry that the service is down.
