### ISSUE TITLE
Clarify analytics access in privacy policy

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#91]
Currently, the privacy policy mentions that the whole Cuberite GitHub team has access to the site analytics, which is not true. Who has access to analytics.cuberite.org at the moment, and is the service actively used?

**Comment by bearbin** [comment]
Currently users able to access the analytics are: 

 * schwertspize
 * @sphinxc0re
 * @worktycho 
 * @madmaxoft

However, it is not actively used, with none of those users logging in in for almost a year. 

I would propose to eliminate it entirely as it's not being used.

**Comment by madmaxoft** [comment]
Huh, I wouldn't even know where to start if I wanted to have a look :P

**Comment by bearbin** [comment]
Just go to https://analytics.cuberite.org and log in (I can reset your password if you've forgotten)

**Comment by madmaxoft** [comment]
Don't really care, I vote remove it.

**Comment by mathiascode** [comment]
If nobody objects, I will remove the analytics code from this repo in a few days/weeks (depending on when I get my workspace moved to a new computer).

**Comment by bearbin** [comment]
In that case, I will also shut down the server and delete all the data,
unless there are any objections from other members of
@cuberite/core-team in the next week.

**Comment by madmaxoft** [comment]
No objections.

**Comment by NiLSPACE** [comment]
No objections here

**Comment by sphinxc0re** [comment]
Go ahead

**Comment by mathiascode** [comment]
I've removed the analytics code from this repo and updated the privacy policy. Pull requests for removal of the code from other repos will be created asap.

**Comment by mathiascode** [comment]
@bearbin The build server seems to have some analytics code that should be removed.

**Comment by bearbin** [comment]
@mathiascode It should now be removed.
