### ISSUE TITLE
Remove HTTPS proxy server

### ISSUE THREAD

**Issue by mathiascode** [cuberite/cuberite.github.io#92]
A few years ago, we decided to put the website behind a proxy server, due to lack of HTTPS support for Github Pages. If things haven't changed since, cuberite.org currently proxies cuberite.github.io. However, Github has since added HTTPS support (LetsEncrypt).

What do you think about serving cuberite.org directly from Github Pages again? It would reduce maintenance burden, and the only regression I can think of would be the lack of HSTS support, which isn't a big deal on a static website in my opinion.

**Comment by bearbin** [comment]
GitHub Pages still doesn't support IPv6, which is stupid, and another thing we would miss out on as well as HSTS. However, I don't think either of those is really going to have an effect and reducing the number of layers of complexity is a good idea.

**Comment by mathiascode** [comment]
Until the AAAA record is removed, an infinite redirect occurs on IPv6 connections due to cuberite.github.io now redirecting to cuberite.org.

**Comment by bearbin** [comment]
This migration is now complete.
