### ISSUE TITLE
Summer 2021 Newsletter

### ISSUE THREAD

**Issue by 12xx12** [cuberite/cuberite.github.io#99]
Maybe for a regular update scedule we could aim for the next newsletter in late july. So there are four newsletter in a year and a resonable develpment progress between the newsletters

**Comment by bearbin** [comment]
Quarterly would be a good schedule, we just need to remember!

**Comment by 12xx12** [comment]
We could set a reminder with a milestone

**Comment by 12xx12** [comment]
It is time (soon)

**Comment by mathiascode** [comment]
The window for this has passed, but we can open a new issue if someone wants to write the next newsletter.
